# Generated by Django 3.1.2 on 2021-01-02 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsphotos',
            name='post_id',
            field=models.ForeignKey(default=None, help_text='Связь, с постом, которому пренадлежит фото', null=True, on_delete=django.db.models.deletion.CASCADE, to='mymodels.posts'),
        ),
    ]
