# Generated by Django 3.1.2 on 2021-01-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodels', '0002_auto_20210102_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_create',
            field=models.DateField(auto_now_add=True, help_text='Дата создания'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(help_text='Имя тега поста', max_length=60, unique=True),
        ),
    ]
