# Generated by Django 3.1.2 on 2021-01-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodels', '0004_auto_20210109_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(default='no', help_text='Текст самого комментария'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='perent_comment_id',
            field=models.IntegerField(blank=True, default='', help_text='id "родительского" комментария, может быть пустым'),
        ),
    ]
