# Generated by Django 3.1.2 on 2021-01-09 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodels', '0006_auto_20210109_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessages',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2021, 1, 9, 14, 45, 12, 78536), help_text='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2021, 1, 9, 14, 45, 12, 80536), help_text='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='perent_comment_id',
            field=models.IntegerField(default=None, help_text='id "родительского" комментария, может быть пустым', null=True),
        ),
        migrations.AlterField(
            model_name='commentsphotos',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2021, 1, 9, 14, 45, 12, 81536), help_text='Дата создания'),
        ),
        migrations.AlterField(
            model_name='evaluationcomments',
            name='date_set',
            field=models.DateField(default=datetime.datetime(2021, 1, 9, 14, 45, 12, 80536), help_text='Дата оценки'),
        ),
        migrations.AlterField(
            model_name='evaluationposts',
            name='date_set',
            field=models.DateField(default=datetime.datetime(2021, 1, 9, 14, 45, 12, 82536), help_text='Дата оценки'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2021, 1, 9, 14, 45, 12, 78536), help_text='Дата создания'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2021, 1, 9, 14, 45, 12, 78536), help_text='Дата создания'),
        ),
        migrations.AlterField(
            model_name='postsphotos',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2021, 1, 9, 14, 45, 12, 81536), help_text='Дата создания'),
        ),
    ]
