# Generated by Django 3.1.2 on 2021-01-09 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mymodels', '0007_auto_20210109_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessages',
            name='date_create',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_create',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата создания'),
        ),
        migrations.AlterField(
            model_name='commentsphotos',
            name='date_create',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата создания'),
        ),
        migrations.AlterField(
            model_name='evaluationcomments',
            name='date_set',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата оценки'),
        ),
        migrations.AlterField(
            model_name='evaluationposts',
            name='date_set',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата оценки'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_create',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата создания'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_create',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата создания'),
        ),
        migrations.AlterField(
            model_name='postsphotos',
            name='date_create',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата создания'),
        ),
    ]
