# Generated by Django 3.1.2 on 2021-01-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodels', '0011_auto_20210109_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата создания'),
        ),
    ]
