# Generated by Django 3.1.2 on 2021-01-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodels', '0014_auto_20210109_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Пометка удаления комментария'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(default='', help_text='Текст самого комментария'),
        ),
    ]
