# Generated by Django 3.1.2 on 2021-02-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymodels', '0018_viewsposts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewsposts',
            unique_together={('post_id', 'user_id')},
        ),
    ]
