# Generated by Django 3.1.2 on 2021-02-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodels', '0019_auto_20210219_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewsposts',
            name='date_set',
        ),
        migrations.AddField(
            model_name='viewsposts',
            name='date_update',
            field=models.DateTimeField(auto_now=True, help_text='Дата просмотра'),
        ),
    ]
