# Generated by Django 3.1.7 on 2021-03-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymodels', '0020_auto_20210220_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_raitinhg',
            new_name='user_rating',
        ),
    ]
