# Generated by Django 3.1.7 on 2021-03-10 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymodels', '0021_auto_20210307_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessages',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата создания'),
        ),
        migrations.AlterField(
            model_name='adminmessages',
            name='name',
            field=models.CharField(blank=True, help_text='Input "Как обращаться"', max_length=150),
        ),
        migrations.AlterField(
            model_name='adminmessages',
            name='user_username',
            field=models.ForeignKey(blank=True, default=None, help_text='Связь со стандартной моделью пользовтеля, может быть null', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
