# Generated by Django 3.1.7 on 2021-03-11 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymodels', '0022_auto_20210310_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessages',
            name='contacts',
            field=models.CharField(blank=True, default=None, help_text='Input "Способ связи"', max_length=500),
        ),
        migrations.AlterField(
            model_name='adminmessages',
            name='name',
            field=models.CharField(blank=True, default=None, help_text='Input "Как обращаться"', max_length=150),
        ),
        migrations.CreateModel(
            name='DeletedPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(blank=True, help_text='Краткая причина удаления', max_length=500)),
                ('full_cause', models.TextField(blank=True, help_text='Полная причина удаления')),
                ('date_deleted', models.DateTimeField(auto_now_add=True, help_text='Дата удаления')),
                ('post_deleted', models.OneToOneField(help_text='Связь с с постом', on_delete=django.db.models.deletion.CASCADE, to='mymodels.posts')),
                ('user_deleted', models.ForeignKey(blank=True, default=None, help_text='Модератор, удаливший пост', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
