# Generated by Django 3.1.7 on 2021-03-11 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymodels', '0024_auto_20210311_1842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostsDeleted',
            new_name='DeletedPosts',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='deleted',
        ),
        migrations.CreateModel(
            name='DeletedComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(blank=True, help_text='Краткая причина удаления', max_length=500)),
                ('full_cause', models.TextField(blank=True, help_text='Полная причина удаления')),
                ('date_deleted', models.DateTimeField(auto_now_add=True, help_text='Дата удаления')),
                ('comment_deleted', models.OneToOneField(help_text='Связь с комментарием', on_delete=django.db.models.deletion.CASCADE, to='mymodels.comments')),
                ('user_deleted', models.ForeignKey(blank=True, default=None, help_text='Модератор, удаливший комментарий', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
