# Generated by Django 3.1.7 on 2021-03-13 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymodels', '0025_auto_20210311_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='heading',
        ),
        migrations.AddField(
            model_name='messages',
            name='type',
            field=models.CharField(blank=True, help_text='Тип сообщения', max_length=100),
        ),
        migrations.AlterField(
            model_name='messages',
            name='text',
            field=models.TextField(help_text='Объект сообщения', max_length=3000),
        ),
        migrations.AlterField(
            model_name='messages',
            name='user_id',
            field=models.ForeignKey(blank=True, default=None, help_text='Получаеть сообщения', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
