# Generated by Django 3.1.7 on 2021-03-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodels', '0026_auto_20210313_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата создания'),
        ),
    ]
