# Generated by Django 3.1.7 on 2021-03-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodels', '0027_auto_20210314_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.SmallIntegerField(default=100, help_text='Номер группы пользователя. 100 - обычный пользователь'),
        ),
    ]
