# Generated by Django 3.1.7 on 2021-03-17 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymodels', '0028_customuser_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='perent_comment_id',
            field=models.ForeignKey(default=None, help_text='id "родительского" комментария, может быть пустым', null=True, on_delete=django.db.models.deletion.CASCADE, to='mymodels.comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(blank=True, default='', help_text='Свзять, коментариев с их авторами', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deletedcomments',
            name='user_deleted',
            field=models.ForeignKey(blank=True, default=None, help_text='Модератор/автор, удаливший комментарий', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deletedposts',
            name='user_deleted',
            field=models.ForeignKey(blank=True, default=None, help_text='Модератор/автор, удаливший пост', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(blank=True, default='', help_text='Автор поста', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
