# Generated by Django 3.1.7 on 2021-03-23 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymodels', '0030_auto_20210320_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminmessages',
            options={'verbose_name': 'Сообщения', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterField(
            model_name='adminmessages',
            name='contacts',
            field=models.CharField(blank=True, default=None, help_text='Input "Способ связи"', max_length=500, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='adminmessages',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата сообщения'),
        ),
        migrations.AlterField(
            model_name='adminmessages',
            name='name',
            field=models.CharField(blank=True, default=None, help_text='Input "Как обращаться"', max_length=150, verbose_name='Как обращаться'),
        ),
        migrations.AlterField(
            model_name='adminmessages',
            name='text',
            field=models.TextField(help_text='Текст сообщения', max_length=3000, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='adminmessages',
            name='user_username',
            field=models.ForeignKey(blank=True, default=None, help_text='Связь со стандартной моделью пользовтеля, может быть null', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_rating',
            field=models.IntegerField(default=0, help_text='Рейтинг комментария', verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='perent_comment_id',
            field=models.ForeignKey(default=None, help_text='id "родительского" комментария, может быть пустым', null=True, on_delete=django.db.models.deletion.CASCADE, to='mymodels.comments', verbose_name='К комментарию'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post_id',
            field=models.ForeignKey(help_text='Свзять, коментариев с постами', on_delete=django.db.models.deletion.CASCADE, to='mymodels.posts', verbose_name='К постам'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(blank=True, default='', help_text='Свзять, коментариев с их авторами', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
