# Generated by Django 3.1.2 on 2020-12-02 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
