# Generated by Django 3.1.2 on 2020-12-03 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20201203_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='tags',
        ),
        migrations.AddField(
            model_name='tags',
            name='posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.posts'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='count_posts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='123456', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
