# Generated by Django 3.1.2 on 2020-12-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20201203_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='posts',
        ),
        migrations.AddField(
            model_name='tags',
            name='posts',
            field=models.ManyToManyField(to='index.Posts'),
        ),
    ]
