# Generated by Django 3.1.2 on 2020-12-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20201205_1036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
