# Generated by Django 3.1.2 on 2020-12-05 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
